version: '3.8'

services:
  # MySQL service එක සම්පූර්ණයෙන්ම අයින් කර ඇත (Cloud MongoDB පාවිච්චි කරන නිසා)

  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8082:8082" # Spring Boot port එක 8082 නිසා
    environment:
      # මෙතනට ඔයාගේ Atlas URI එක ඇතුළත් කරන ලදී
      - SPRING_DATA_MONGODB_URI=mongodb+srv://it23600898_smart_db:SmartCampus123@cluster0.mg148jy.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

# පරණ mysql_data volume එක අවශ්‍ය නැති නිසා ඉවත් කරන ලදී